version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports: 
    - "6385:5672"
    - "8095:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=shimond
      - RABBITMQ_DEFAULT_PASS=Aa12345678
  sqlserver:
    image: microsoft/mssql-server-linux:latest
    volumes:
      - sqlserverdata:/var/opt/mssql
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_PID=Developer
      - SA_PASSWORD=8jkGh47hnDw89Haq8LN2

  timerworkerservice:
    image: ${DOCKER_REGISTRY-}timerworkerservice
    build:
      context: .
      dockerfile: TimerWorkerService/Dockerfile
