version: '3.4'

services:

  sqlserver-catgalog:
    container_name: sqlserver-catgalog
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - sqlserverdata:/var/opt/mssql
    ports:
      - "1455:1433"
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_PID=Developer
      - SA_PASSWORD=8jkGh47hnDw89Haq8LN2

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports: 
    - "6385:5672"
    - "8095:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=shimond
      - RABBITMQ_DEFAULT_PASS=Aa12345678
  
  timerworkerservice:
    image: ${DOCKER_REGISTRY-}timerworkerservice
    build:
      context: .
      dockerfile: TimerWorkerService/Dockerfile
    depends_on:
        - rabbitmq
      
  emailservice:
    image: ${DOCKER_REGISTRY-}emailservice
    build:
      context: .
      dockerfile: Services/EmailService/Dockerfile
    depends_on:
        - rabbitmq
      
  redis:
    container_name: basket-redis
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
   
  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/CatalogAPI/Dockerfile

  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/BasketAPI/Dockerfile

volumes:
  sqlserverdata:
    external: false    



