version: '3.4'

services:

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports: 
    - "6385:5672"
    - "8095:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=shimond
      - RABBITMQ_DEFAULT_PASS=Aa12345678
  
  timerworkerservice:
    hostname: timerworkerservice
    image: ${DOCKER_REGISTRY-}timerworkerservice
    build:
      context: .
      dockerfile: TimerWorkerService/Dockerfile
      
  emailservice:
    hostname: emailservice
    image: ${DOCKER_REGISTRY-}emailservice
    build:
      context: .
      dockerfile: Services/EmailService/Dockerfile

volumes:
  sqlserverdata:
    external: false    

